### PR TITLE
Add bsky

### PR DESCRIPTION
**Pull request by dholbach**
Needs #146 to be merged first.

### CODE REVIEW

**Comment by evrardjp** [comment]
Slack for weaveworks is still present, would you mind adding a fix commit or a fix MR first ?

**Comment by dholbach** [comment]
> Slack for weaveworks is still present, would you mind adding a fix commit or a fix MR first ?

Where? In the old meeting logs?

**Comment by dholbach** [comment]
Ok, resolved it now.

**Comment by evrardjp** [comment]
LGTM

**Review by evrardjp — APPROVED** [review]

**Pull request merged**
