### PR TITLE
blog: learning-the-ropes-of-being-a-maintainer

### PR DESCRIPTION
**Pull request by dholbach**

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
This is a great first post, lgtm!

**Review by ckotzbauer — APPROVED** [review]
Great post, I like it :heart:

**Comment by evrardjp** [comment]
I like the concept!

I am afraid some of it might become outdated with the code changes. I believe code structure should be in another place (contributing.md or architecture reference), and we should simply point to it. WDYT?

WDYT about mentioning the rate of changes (and their releasing) and our mentality? I think mentioning "feature complete" is something important, and the rest is janitorial and/or slight inprovements. This is useful as we don't want someone proposing a complete change in the main repo, but rather small improvements, while we are open to discuss larger mindset changes for the same topic which could land in the same org and different repo.

**Comment by ckotzbauer** [comment]
I agree, I think we can elaborate a bit more about the rate of changes and their size in the last months.
"Feature complete" is a phrase, we should be a bit careful, I guess. I know we're not planning to integrate completely new or bigger features, but as there are many issues open right now which are requesting several improvements and add new ideas, I think we maybe would shock a part of the community and force to search for other solutions. WDYT?

**Comment by dholbach** [comment]
I moved some of the directory structure bits to: https://github.com/kubereboot/kured/pull/964

**Review by evrardjp — APPROVED** [review]
While I am not in favour of mentioning "flame and glory" (maintaining is not glorious or doesn't attract fame), I believe that ppl reading this will get a vibe of our humourous stances, which is good enough. Let's go.

**Comment by dholbach** [comment]
Thanks for the reviews! I'll put some more work into it.

**Review by evrardjp — APPROVED** [review]
Great, thanks for the blog post @dholbach !

**Comment by evrardjp** [comment]
CI issues were related to the fact the link for this new page is not yet existing, so that's fine.

**Pull request merged**
