### PR TITLE
Import meeting minutes

### PR DESCRIPTION
**Pull request by evrardjp**

### CODE REVIEW

**Review by dholbach — APPROVED** [review]

**Comment by evrardjp** [comment]
Those links are dead in the current meeting minutes, maybe we should update them or remove them. 
If you're okay, I will remove the links to github forks (for example dholbach's repositories), remove google docs links.

**Comment by evrardjp** [comment]
I removed dead links in advance, but I can remove the last commit if we really want to. (Daniel, if you can find  2021-12-01 upload, that would be lovely, but it's alright if you can't :) )

**Review by dholbach — DISMISSED** [review]

**Comment by evrardjp** [comment]
Pushed an update, did a poopoo on the alphabetical order at 11pm yesterday.

**Review by dholbach — APPROVED** [review]

**Comment by evrardjp** [comment]
@ckotzbauer @jackfrancis  ok for you to merge as is?

**Review by ckotzbauer — APPROVED** [review]
Thanks for the import, looks very good!

**Pull request merged**
