### PR TITLE
Add 20240606 meeting minutes

### PR DESCRIPTION
**Pull request by evrardjp**
Here is a summary of what happened at last meeting.

### CODE REVIEW

**Comment by evrardjp** [comment]
This should probably wait for #119  to merge first.

**Review by dholbach — APPROVED** [review]

**Comment by evrardjp** [comment]
@ckotzbauer  @jackfrancis

**Review by ckotzbauer — APPROVED** [review]

**Comment by evrardjp** [comment]
I will rebase this and request a new vote if you're okay. Sorry for the late merging of others MRs - I assumed I shouldn't merge my own code ... and forgot our rules when I have enough votes :)

**Comment by evrardjp** [comment]
@ckotzbauer  could you have a look if it's still okay for you? Nothing changed, but in case I did a poo poo with the merge rebase tool.

**Review by ckotzbauer — APPROVED** [review]
go for it!

**Pull request merged**
